# Generated by Django 4.0.5 on 2022-07-01 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poebota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_autor', models.CharField(max_length=50, verbose_name='Автор')),
                ('book_janr', models.CharField(max_length=50, verbose_name='Жанр')),
                ('book_izdat', models.CharField(max_length=50, verbose_name='Издатель')),
                ('book_name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Bron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bron_status', models.CharField(max_length=50, verbose_name='Забронирована')),
                ('bron_time', models.DateTimeField()),
                ('bron_password', models.CharField(max_length=50, verbose_name='Пароль для бронирования')),
                ('bron_login', models.CharField(max_length=50, verbose_name='Логин')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poebota.book')),
            ],
        ),
        migrations.DeleteModel(
            name='Count',
        ),
        migrations.DeleteModel(
            name='Object',
        ),
    ]
