# Generated by Django 4.0.5 on 2022-07-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poebota', '0002_book_bron_delete_count_delete_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bron',
            name='bron_status',
            field=models.CharField(default='Нет', max_length=50, verbose_name='Забронирована'),
        ),
    ]
