# Generated by Django 4.0.5 on 2022-07-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poebota', '0003_alter_bron_bron_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bron',
            name='bron_time',
            field=models.DateTimeField(default=None),
        ),
    ]
